### ISSUE TITLE
Add ability to disable Rankings page

### ISSUE THREAD

**Issue by datitisev** [FriendsOfFlarum/gamification#1]
> From https://github.com/ReFlar/gamification/issues/49
> 
> At the moment, there is a rankings page that ranks users by the number of points that they have acquired on the forum. This is assumed to be a default desired feature of the gamification extension. I would appreciate it if you added the ability to disable this Rankings Page from the admin panel.

**Comment by Ralkage** [comment]
This was added to previous release and can be configured in the Admin area under the Gamification permissions. The label for this permission is called "See ranking page".
