### ISSUE TITLE
Give the users ability to turn off notifications for upvotes/downvotes

### ISSUE THREAD

**Issue by studosi-flarum** [FriendsOfFlarum/gamification#10]
As the title says, my users noticed that while fof/reaction has the option to ignore reactions, fof/gamification does not have an option to turn off upvote/downvote notifications. I also think this option should be added, even though the system to prevent notification spam is pretty elegant as-is.

**Comment by Ralkage** [comment]
We’ll look into this feature request as soon as we can :)

**Comment by imorland** [comment]
Available in `1.2.3`
