### ISSUE TITLE
Display position is wrong

### ISSUE THREAD

**Issue by heidongwang** [FriendsOfFlarum/gamification#12]
![image](https://user-images.githubusercontent.com/59247295/80122986-dad79d00-85c0-11ea-998f-8afedd6bc51f.png)

**Comment by datitisev** [comment]
Are you talking about the overlapping with the tags? Sorry, need clarification here.

**Comment by heidongwang** [comment]
Yes, likes and tags overlap。I am using the default theme

**Comment by datitisev** [comment]
Fixed in c586065b500eedfc08ee9b9a829b19bb3bdceab5.
