### ISSUE TITLE
Rankingpage should not show the tags.

### ISSUE THREAD

**Issue by s1-ranjan** [FriendsOfFlarum/gamification#14]
As of now the ranking page is showing all the tags, as shown bellow...
![Screenshot from 2020-06-20 16-31-39](https://user-images.githubusercontent.com/20767253/85200563-20d98480-b316-11ea-8cb6-bdafe933a21b.png)
The page does not look Good on large screen, where as if this page is not allowed to shows the tags it looks good as shown bellow..
![Screenshot from 2020-06-20 16-30-55](https://user-images.githubusercontent.com/20767253/85200604-8a599300-b316-11ea-8714-51b6337bb8a0.png)
Hence it would be a good idea to not to show the tags in the ranking page.

**Comment by ScottBeeson** [comment]
Just installed the extension 5 minutes ago, this was the first thing I noticed that I didn't like.  

+1
