### ISSUE TITLE
Standings button problem

### ISSUE THREAD

**Issue by ghost** [FriendsOfFlarum/gamification#18]
The page does not open when the guests click on the standings button. You can test it from the link.
https://forum.sourceturk.net

**Comment by datitisev** [comment]
Hm, check your permissions. If guests cannot view rankings page, then that is the bug and the button shouldn't be shown.

**Comment by northeaster** [comment]
![image](https://user-images.githubusercontent.com/55854510/88345876-a7d3af80-cd4f-11ea-8cc5-634a4878f1ea.png)

**Comment by datitisev** [comment]
I can reproduce this.

**Comment by northeaster** [comment]
![image](https://user-images.githubusercontent.com/55854510/88346065-27617e80-cd50-11ea-8b47-32bcc113cecd.png)

![image](https://user-images.githubusercontent.com/55854510/88346086-334d4080-cd50-11ea-9f37-0d469f8ae444.png)

Those who have the role of the button in sidebar should see. Now everyone sees the button. It gives the error "You do not have permission to do that."

**Comment by northeaster** [comment]
https://forum.sourceturk.net/kategoriler if you click on the **Rankings** button while in the link, it opens the discussions page. You can test it.

**Comment by EvilExecutor** [comment]
Hello! 

This issue is resolved by FriendsOfFlarum/gamification v0.3.3 & the "everyone" permission has been removed from "See Ranking Page". Thanks for reporting this!
