### ISSUE TITLE
Cannot add images for trophies

### ISSUE THREAD

**Issue by 01fbk** [FriendsOfFlarum/gamification#21]
I have just installed this extension and I want to add images to my 1st place, 2nd place, 3rd place trophies.
Whenever I add an image, it says: The requested resource was not found.

The image is taken from flaticon.com and it is a 64x64px png image.
Is there a specific size / file type that we need to use ?

I have also posted this question on https://discuss.flarum.org/d/20671-friendsofflarum-gamification/244
According to luceos , this can be a permission to the storage directory that gamification uses, although he is not sure which one that is. Can you assist ?

Thank you,
Cristian

**Comment by onyxcode** [comment]
I am also having this issue.

**Comment by onyxcode** [comment]
![image](https://user-images.githubusercontent.com/58049576/91204870-aab91b80-e6d2-11ea-913a-daa94f1030c0.png)
