### ISSUE TITLE
Migration of permissions is incomplete

### ISSUE THREAD

**Issue by iPurpl3x** [FriendsOfFlarum/gamification#22]
Whit commit 6d2e4a07d343c232aa1fc42351e323e58ce9c523 @datitisev you made [a migration](https://github.com/FriendsOfFlarum/gamification/blob/6d2e4a07d343c232aa1fc42351e323e58ce9c523/migrations/2020_07_11_000000_change_permission_name.php) to rename permissions. 
Here you missed that permissions can be made on individual tags, so there should have been something like `->where('permission', 'like', '%discussion.vote')`

**Comment by datitisev** [comment]
🤦 Nice catch! Thanks for reporting it; will have to update the migration soon.

**Comment by datitisev** [comment]
Closed with 12f03ae9320ce8a2c7a9133f9d58d17e1974875d.
