### ISSUE TITLE
Is there a plan to update?

### ISSUE THREAD

**Issue by XiaoPika** [FriendsOfFlarum/gamification#25]
Flarum Core Beta14... can not use it yet,
is there help to update?

**Comment by xwiz** [comment]
I'm also interested in this. Any pointers/guide on how I can achieve this?

**Comment by Kolomona** [comment]
An update would be awesome. This is the only extension holding me back from upgrading flarum.

**Comment by Matt4499** [comment]
Same.

**Comment by karaok491** [comment]
Beta 14 is now supported from `0.3.1`
