### ISSUE TITLE
Add option to disable up-voting or down-voting

### ISSUE THREAD

**Issue by Ralkage** [FriendsOfFlarum/gamification#3]
As inspired by [this user getting their hands dirty with the dist file for this extension](https://discuss.flarum.org/d/21006-new-to-flarum-how-do-i-modify-an-extension), I think it would be a good idea to add a switch or something to enable or disable the up-voting or down-voting actions 🙈 

Thoughts, @CDK2020?

**Comment by CDK2020** [comment]
What's the point of the extension w/o upvoting or downvoting? Everything revolves around that

**Comment by Ralkage** [comment]
@CDK2020 some communities simply want to promote certain actions depending on the audience (almost like Facebook only having "Likes" and not "Dislikes" before reactions came across).

Another example would be the [Bunq community](https://together.bunq.com/), they only have one action available which is the up-vote option. 

![image](https://user-images.githubusercontent.com/2059356/62829517-95f40d80-bbcd-11e9-98d1-463337fde0f3.png)

I'm sure they had to so something extra to remove down-voting, LESS/CSS most likely from the looks of it. It's also interesting to see the different implementations of Gamification other communities are using since "gamification" covers a variety of activities, why not allow them to have the option anyway so they could stray away from modifying any code or using other tricks to achieve a similar outcome?

**Comment by tksham** [comment]
Hi I am the original poster.

I want the action to be customisable in the case of hoping to have a special meaning on the upvotes.

Instead a low commitment of pressing a “like”, I would like to introduce the delta system (https://changemyview.net/subreddit/#delta-system) which has a different meaning of “agreeing” or “liking” the reply.

Hope it makes sense.

**Comment by CDK2020** [comment]
So switches to disable upvotes and downvotes individually would work?

**Comment by tksham** [comment]
Need disable, enable as well as choosing the label and icon for the buttons

**Comment by Ralkage** [comment]
@tksham ahhh I see what you mean by the icons as well.

@CDK2020 basically having the option to disable/enable up-voting and down-voting individually as well as choosing separate icons instead of just one icon as far as the implementation is now. It makes sense to make this change because it aligns this extension with the whole gamification concept even more and gives users more configurations.

**Comment by tksham** [comment]
@Ralkage @CDK2020 
I succeeded in modifying few lines of code in order to temporarily achieve what I want with minimum effort (no admin setting for customisation yet)

http://139.162.30.55/d/14-meeting-minutes-from-1st-hackathon

Is there any rules or guidelines so that I can contribute to my own request?
Simply create my own feature branch locally and then make a pull request?
(Sorry I am new to npm, composer and the whole github community)
