### ISSUE TITLE
Tag-based voting / permission bug?

### ISSUE THREAD

**Issue by tipa** [FriendsOfFlarum/gamification#32]
I would like to use the gamification/voting based in my forums, but *only* on discussions that were tagged with the "Feature Request" tag. I've set up the tags like shown here:
![image](https://user-images.githubusercontent.com/2863198/107143587-27b11800-6936-11eb-83ff-7f66c14caafb.png)
![image](https://user-images.githubusercontent.com/2863198/107143597-2e3f8f80-6936-11eb-9af7-f1cbcca2c9b3.png)

However, the feature seems to be enabled for all discussions, not only the "Feature Request" ones.

**Comment by datitisev** [comment]
What account did you test it with? Admins have all permissions, so they'll still be able to upvote/downvote & see upvotes/downvotes in any tag.

**Comment by tipa** [comment]
I tested it with a normal user/"member" account - are you not able to reproduce the problem?

**Comment by datitisev** [comment]
I haven't tested it, was just making sure.
