### ISSUE TITLE
Bug on flarum toggles

### ISSUE THREAD

**Issue by justoverclockl** [FriendsOfFlarum/gamification#33]
Here the discussion about the bug
https://discuss.flarum.org/d/26194-bug-on-auto-follow-discussion/16

**Comment by Ralkage** [comment]
@justoverclockl  are you able to provide any screenshots of your FoF Gamification Admin settings? Still trying to replicate this issue and wondering if it may be due to some values you may have set that Gamification doesn't like :(

**Comment by justoverclockl** [comment]
> @justoverclockl  are you able to provide any screenshots of your FoF Gamification Admin settings? Still trying to replicate this issue and wondering if it may be due to some values you may have set that Gamification doesn't like :(

I can't because now I'm on beta 16 and this extension is no longer supported 😔

**Comment by Ralkage** [comment]
@justoverclockl now that it's out for v1, are you still able to replicate this issue?

**Comment by imorland** [comment]
Closing as stale. Please feel free to re-open if this is still an issue for you
