### ISSUE TITLE
Bug on /vendor/fof/gamification/src/Gamification.php::calculateHotness ?

### ISSUE THREAD

**Issue by fstln-joe** [FriendsOfFlarum/gamification#34]
on line 45: $date = strtotime($discussion->start_time);
table `discussions` do not have column `start_time`, but has `created_at`. 
Should it be replaced with "$discussion->created_at"?

Flarum version:  0.1.0-beta.15

**Comment by Ralkage** [comment]
Good catch! This was changed [some time after](https://github.com/flarum/core/blob/master/migrations/2018_01_11_155200_change_discussions_rename_columns.php#L16) Gamification was conceived; we'll have this either fixed in a patch or just include it in our beta 16 update ;)
