### ISSUE TITLE
Only my settings data not being rendered

### ISSUE THREAD

**Issue by Bishwas-py** [FriendsOfFlarum/gamification#37]
Only my profile isn't being rendered as an admin in the forum whether `FOF/gamification` is enabled, except me everyone's profile is fine. Even other admins are able to use their settings, but not me. Why is this issue occuring? And how am I supposed to fix this issue?

This is the message I am getting in the console.
```
3   TypeError: Cannot read property 'key' of undefined              mount-redraw.js:15 
    at h (render.js:314)
    at render.js:477
    at f (render.js:416)
    at h (render.js:302)
    at render.js:477
    at f (render.js:416)
    at h (render.js:302)
    at render.js:477
    at f (render.js:416)
    at h (render.js:302)
```

> We use flarum-beta 16 in our forum 😀 

You can also check my forum here: https://webmatrices.com/u/bishwasbh

https://imgur.com/a/3aNUexM

**Comment by Ralkage** [comment]
Can you post the output of `php flarum info` from the root of your Flarum installation? It would help to know what other extensions are installed on your forum so we can try and replicate this issue :)

**Comment by Bishwas-py** [comment]
@Ralkage 
Here it is...
```
Flarum core 0.1.0-beta.16
PHP version: 7.4.16
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, i360, bcmath, dba, dom, enchant, fileinfo, gd, imap, intl, json, ldap, exif, mysqli, mysqlnd, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, snmp, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, yaml, zip
+-----------------------------------+------------------+--------+
| Flarum Extensions                 |                  |        |
+-----------------------------------+------------------+--------+
| ID                                | Version          | Commit |
+-----------------------------------+------------------+--------+
| flarum-subscriptions              | v0.1.0-beta.16   |        |
| flarum-tags                       | v0.1.0-beta.16   |        |
| flarum-markdown                   | v0.1.0-beta.16.1 |        |
| flarum-flags                      | v0.1.0-beta.16   |        |
| flarumite-simple-discussion-views | 0.3.0            |        |
| askvortsov-moderator-warnings     | v0.5.0           |        |
| fof-user-directory                | 0.6.1            |        |
| fof-user-bio                      | 0.5.0            |        |
| fof-masquerade                    | 0.4.0            |        |
| fof-follow-tags                   | 0.7.2            |        |
| nearata-cakeday                   | v1.3.0           |        |
| askvortsov-rich-text              | v1.1.1           |        |
| fof-polls                         | 0.4.1            |        |
| fof-upload                        | 0.14.0           |        |
| v17development-seo                | v1.7.2           |        |
| fof-best-answer                   | 0.4.0            |        |
| flarum-statistics                 | v0.1.0-beta.16   |        |
| flarum-pusher                     | v0.1.0-beta.16   |        |
| flarum-suspend                    | v0.1.0-beta.16   |        |
| flarum-sticky                     | v0.1.0-beta.16   |        |
| flarum-mentions                   | v0.1.0-beta.16   |        |
| flarum-lock                       | v0.1.0-beta.16   |        |
| flarum-lang-english               | v0.1.0-beta.16   |        |
| flarum-emoji                      | v0.1.0-beta.16   |        |
| flarum-bbcode                     | v0.1.0-beta.16   |        |
| flarum-approval                   | v0.1.0-beta.16   |        |
| fof-analytics                     | 0.12.0           |        |
| fof-drafts                        | 0.4.0            |        |
| fof-sitemap                       | 0.7.0            |        |
| fof-oauth                         | 0.3.0            |        |
| fof-pretty-mail                   | 0.4.0            |        |
| askvortsov-markdown-tables        | v1.0.1           |        |
| ffans-clipboardjs                 | v0.1.0-beta.16.1 |        |
| fof-links                         | 0.6.0            |        |
| fof-share-social                  | 0.3.1            |        |
| fof-username-request              | 0.5.0            |        |
| fof-formatting                    | 0.4.0            |        |
| v17development-user-badges        | v0.1.2           |        |
| fof-gamification                  | 0.5.0            |        |
| ianm-html-head                    | 0.2.0            |        |
+-----------------------------------+------------------+--------+
Base URL: https://webmatrices.com
Installation path: /path/webmatrices.com
Debug mode: off

```

**Comment by Bishwas-py** [comment]
Why is noone replying?

**Comment by Ralkage** [comment]
@Bishwas-py please be patient with us as we are preparing our extensions for the big 1.0 release :) we will address this issue and many others as soon as we sort out the updates/

**Comment by Bishwas-py** [comment]
> @Bishwas-py please be patient with us as we are preparing our extensions for the big 1.0 release :) we will address this issue and many others as soon as we sort out the updates/

Is this fixed brother?

**Comment by joshuapack** [comment]
@Bishwas-py I have seen this behavior before. The current reason, at least for me, was due to my profile had more ranks then what I had in the view. Change `How many rank badges should be shown?` to the max number of ranks fixed the issue for me.

**Comment by Bishwas-py** [comment]
> @Bishwas-py I have seen this behavior before. The current reason, at least for me, was due to my profile had more ranks then what I had in the view. Change `How many rank badges should be shown?` to the max number of ranks fixed the issue for me.

Yupp, that `How many rank badges should be shown?` fixed the issue. 

### What I did is:
1. I have max 5 number of badges
2. I changed `How many rank badges should be shown?` to 5
3. and it got fixed

but I only wanna set max badge to three and if I did so, it'll surely cause that issue. Not only on my profile, on the profile of people with more than 3 badges.

**Comment by Ralkage** [comment]
> 
> 
> @Bishwas-py I have seen this behavior before. The current reason, at least for me, was due to my profile had more ranks then what I had in the view. Change `How many rank badges should be shown?` to the max number of ranks fixed the issue for me.

Thanks for the info! This will surely help with reproducing and hopefully fixing this dreaded issue with user profiles not loading :) https://github.com/FriendsOfFlarum/gamification/commit/f04cd600d084ba9cb4709cef8d8934fa293d78a7 might cover this fix and we're hoping to have [this PR](https://github.com/FriendsOfFlarum/gamification/pull/43) fully reviewed soon. We do apologize that this is taking a long time as I'm sure you know that development of any kind takes time and patience so that we don't end up merging and releasing something that is still broken :( we also have a QA team within FriendsOfFlarum so it is always good to have QA check and approve before we release anything new. Thank you for your time and patience everyone!

**Comment by imorland** [comment]
Closing as stale. Please feel free to re-open if this is still an issue for you
