### ISSUE TITLE
Error in javascript on load profile

### ISSUE THREAD

**Issue by darkfoxdeveloper** [FriendsOfFlarum/gamification#4]
With this error cannot view profile and the extension not work. Using Beta 9.
This is the error:
```
AddAttributes.js:31 Uncaught TypeError: Cannot read property 'children' of null
    at o (AddAttributes.js:31)
    at AddAttributes.js:37
    at Array.forEach (<anonymous>)
    at o (AddAttributes.js:36)
    at AddAttributes.js:37
    at Array.forEach (<anonymous>)
    at o (AddAttributes.js:36)
    at AddAttributes.js:37
    at Array.forEach (<anonymous>)
    at o (AddAttributes.js:36)
```

The current file:
![image](https://user-images.githubusercontent.com/46323771/66227509-985e7980-e6dd-11e9-8b8a-57db1381d3df.png)

Update: **I Disabled the "Profile views" plugin and work partially!**
Error on vote: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'last_vote_time' in 'field list'

**Comment by Ralkage** [comment]
@darkfoxdeveloper still having this issue?

Any relevant logs you can post?

Can you also post the output of `php flarum info` ran from the roof of your Flarum installation?

**Comment by darkfoxdeveloper** [comment]
Output of php flarum info:

![image](https://user-images.githubusercontent.com/46323771/66227386-61886380-e6dd-11e9-9d36-55a751d35611.png)

Code js help image:
![image](https://user-images.githubusercontent.com/46323771/66227509-985e7980-e6dd-11e9-8b8a-57db1381d3df.png)

**Comment by datitisev** [comment]
No longer relevant. JS error was fixed some time ago.
