### ISSUE TITLE
Unable to enable the module

### ISSUE THREAD

**Issue by NicoKuroKusagi** [FriendsOfFlarum/gamification#41]
## Bug Report

**Current Behavior**
It is impossible to enable the module, the logs say the follwing:

`Next Illuminate\Database\QueryException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'value' (SQL: alter table `flarum_post_votes` add `value` int not null default '0') in /flarum/app/vendor/illuminate/database/Connection.php:692
Stack trace:
#0 /flarum/app/vendor/illuminate/database/Connection.php(652): Illuminate\Database\Connection->runQueryCallback()
#1 /flarum/app/vendor/illuminate/database/Connection.php(486): Illuminate\Database\Connection->run()
#2 /flarum/app/vendor/illuminate/database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement()
#3 /flarum/app/vendor/illuminate/database/Schema/Builder.php(365): Illuminate\Database\Schema\Blueprint->build()
#4 /flarum/app/vendor/illuminate/database/Schema/Builder.php(212): Illuminate\Database\Schema\Builder->build()
#5 /flarum/app/vendor/fof/gamification/migrations/2020_07_09_000000_change_post_votes_type_column.php(20): Illuminate\Database\Schema\Builder->table()
#6 [internal function]: Illuminate\Filesystem\Filesystem::{closure}()
#7 /flarum/app/vendor/flarum/core/src/Database/Migrator.php(202): call_user_func()
#8 /flarum/app/vendor/flarum/core/src/Database/Migrator.php(133): Flarum\Database\Migrator->runClosureMigration()
#9 /flarum/app/vendor/flarum/core/src/Database/Migrator.php(116): Flarum\Database\Migrator->runUp()
#10 /flarum/app/vendor/flarum/core/src/Database/Migrator.php(90): Flarum\Database\Migrator->runMigrationList()
#11 /flarum/app/vendor/flarum/core/src/Extension/Extension.php(482): Flarum\Database\Migrator->run()
#12 /flarum/app/vendor/flarum/core/src/Extension/ExtensionManager.php(311): Flarum\Extension\Extension->migrate()
#13 /flarum/app/vendor/flarum/core/src/Extension/ExtensionManager.php(182): Flarum\Extension\ExtensionManager->migrate()
#14 /flarum/app/vendor/flarum/core/src/Api/Controller/UpdateExtensionController.php(46): Flarum\Extension\ExtensionManager->enable()
#15 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\UpdateExtensionController->handle()
#16 /flarum/app/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#17 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ExecuteRoute->process()
#18 /flarum/app/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#19 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\ThrottleApi->process()
#20 /flarum/app/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#21 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process()
#22 /flarum/app/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle()
#23 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ResolveRoute->process()
#24 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#25 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#26 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(56): Laminas\Stratigility\Next->handle()
#27 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#28 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#29 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#30 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#31 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#32 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#33 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#34 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#35 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process()
#36 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#37 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#38 /flarum/app/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#39 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#40 /flarum/app/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#41 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\InjectActorReference->process()
#42 /flarum/app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#43 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#44 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#45 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#46 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#47 /flarum/app/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#48 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#49 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#50 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#51 /flarum/app/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#52 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ProcessIp->process()
#53 /flarum/app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#54 /flarum/app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#55 /flarum/app/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#56 /flarum/app/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#57 /flarum/app/public/index.php(26): Flarum\Http\Server->listen()
#58 {main}`

**Steps to Reproduce**
1. Enable the addon in ACP

**Expected Behavior**
The enable should work?

**Environment**
- Flarum version: 1.0.2
- Extension version: latest
- Webserver: openresty
- Hosting environment: Kubernetes
- PHP version: 8.0.6

**Comment by datitisev** [comment]
Think something might have gone wrong with DB? We only create the `value` column once.

https://github.com/FriendsOfFlarum/gamification/blob/5f35ab591645906945bee0cee97ea58736c029b1/migrations/2020_07_09_000000_change_post_votes_type_column.php#L18-L20

If you have values in that column, try to add `2020_07_09_000000_change_post_votes_type_column.php` to migrations table so iot doesn't run - if you don't have any values (they're all 0) you should be able to just delete the column. 

All of this with a nearby backup, of course.

**Comment by Ralkage** [comment]
Hi @NicoKuroKusagi, have you tried what @datitisev suggested above?
