### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) api :ranks(1)

### ISSUE THREAD

**Issue by Leleuchzhang** [FriendsOfFlarum/gamification#5]
when I custom rank and click the add button 
Failed to load resource: the server responded with a status of 404 (Not Found)
mithril.js:2191 POST https://gametogeek.club/api/ranks 404 (Not Found)
(anonymous) @ mithril.js:2191
(anonymous) @ mithril.js:2199
m.request @ mithril.js:2288
e.request @ Application.js:300
e.save @ Model.js:160
n.addRank @ SettingsPage.js:243
Y.t.<computed> @ mithril.js:1286

**Comment by Leleuchzhang** [comment]
I use beta 10

**Comment by datitisev** [comment]
One of the extensions you're using is probably resolving the `UrlGenerator ` too early...

**Comment by Ralkage** [comment]
@Leleuchzhang is this still an issue for you? Are you on the latest version of Flarum and FoF Gamification? I'll keep this issue open for 72 hours to give you enough time to respond before I close this :)
