### ISSUE TITLE
Crashes flarum once u active plugin

### ISSUE THREAD

**Issue by 32bitx64bit** [FriendsOfFlarum/gamification#50]
Once activated crashes flarum main page (Once deactivated flarum main page is back up) 

Please fix

**Comment by datitisev** [comment]
We need more information to do anything about this.

Flarum version, extension version, error (either JS in Developer Tools > Console, or PHP in `storage/logs/flarum-<date>.log`), etc...

**Comment by datitisev** [comment]
Can you define "crashes"? What exactly happens? Or, doesn't happen?

**Comment by datitisev** [comment]
Hm, this is not much to go off of, especially as nobody else has reported the same issue as far as I'm aware...

**Comment by imorland** [comment]
@32bitx64bit can you please update to `1.2.0` and let me know if this is still an issue for you?

**Comment by imorland** [comment]
Closing as stale, feel free to re-open if it's still a problem for you.
