### ISSUE TITLE
Disable Ranking label menu if Permission not allow to Everyone

### ISSUE THREAD

**Issue by leguennecj** [FriendsOfFlarum/gamification#8]
Hello,
I have an issue concerning Ranking.
Indeed, it's works only for connected members even if I select "Everyone" for "See ranking page" on the permission settings.
Please have a look: www.batteries-forum.com

2 solutions:

- hide the "Ranking" menu on left for no-connected people if I parameter "Members" on permissions setting
- make possible to open the page Rankings page for everyone (https://www.batteries-forum.com/rankings)

Regards

**Comment by karaok491** [comment]
Thank you for raising this, this is handled in the next release :)
