### ISSUE TITLE
The phone's display is out of place

### ISSUE THREAD

**Issue by cc2562** [FriendsOfFlarum/gamification#9]
![](https://s2.ax1x.com/2020/01/14/lq54m9.jpg)
Computer says it's working. But it's misaligned on the phone

**Comment by tipa** [comment]
Came here to report the same issue. Unfortunate to see that this problem hasn't been dealt with for over a year.

**Comment by Ralkage** [comment]
I can confirm this is still an issue @cc2562 @tipa we'll get this fixed :D
